### PR TITLE
Implement openapi 3.0 specification.

### PR DESCRIPTION
**Pull request by rmlopes**
Plus:
Add sub-resource path parameters documentation. 
Add security definitions for eve-oauth extension. 
Use resource example only for requestBody parameters (responses use the schema based example).
Add reusable IfMatch parameter.

Open to discussion.

### CODE REVIEW

**Comment by sergekir** [comment]
Any plans on merging it?

**Comment by nicolaiarocci** [comment]
Yes, I plan on reviewing this (and other stuff) once I have some extra time to work on the eve ecosystem.

**Comment by nicolaiarocci** [comment]
Howdy!

I am sorry for the long wait @rmlopes and @sergekir. Since some time has passed, do any of you have anything to add/comment about this pull request?

**Comment by rmlopes** [comment]
Hi Nicola,

I have kept a branch for this PR and in the meanwhile have made other improvements that I needed for my project. These included support for the `valueschema` properties and support for static documentation using `redoc`. I just merged them into master this morning and I can create another PR for comparison if you wish. I think it is still pertinent whether this should be an upgrade for eve-swagger or rather a new extension.

**Comment by nicolaiarocci** [comment]
Please submit a new PR, I will gladly review it.

**Comment by nicolaiarocci** [comment]
@rmlopes ping, just to make sure work is still ongoing here.

**Pull request closed without merging**
