### PR TITLE
add GET query params and add authorization

### PR DESCRIPTION
**Pull request by JoveYu**
add GET query params
1. where
2. sort
3. page
4. max_results

add authorization
1. basic auth
2. bearer auth

fix servers
1. allow to use SWAGGER_HOST https server
2. add `URL_PREFIX` `API_VERSION` support

fix GET resource
1. response change to array with `_items` from object

### CODE REVIEW

**Comment by JoveYu** [comment]
BTW, I hava no idea with oauth auth

**Comment by nicolaiarocci** [comment]
rebased and merged, thanks.

**Comment by luiscoms** [comment]
Any plans to release it?

**Comment by nicolaiarocci** [comment]
yep

**Pull request closed without merging**
